version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  build:
    commands:
      - docker build -t sae .
      - docker tag sae 845035073542.dkr.ecr.us-east-2.amazonaws.com/sae:latest
  post_build:
    commands:
      - docker push 845035073542.dkr.ecr.us-east-2.amazonaws.com/sae
artifacts:
  files:
    - Dockerrun.aws.json
    - imagedefinitions.json
